/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab2_andres_gonzalez_david_buelvas_nombre3_apellido3_.nombre4_apellido4_.nombre5_apellido5;

import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author HP
 */
public class CRYPTOBREAKER extends javax.swing.JFrame {

    char[] mensajeCifrado = {'K','R','R','H'};   
    int tiempo = 60;
    boolean jugando = false;
    Timer timer;
    /**
     * Creates new form CRYPTOBREAKER
     */
    public CRYPTOBREAKER() {
        initComponents();
        setResizable(false);
        lblTiempo.setText("Tiempo: 60");
        crearTimer();
        setLocationRelativeTo(null);
    }

    private String desencriptar(char[] m) {
        String resultado = "";
        for (char c : m) {
            char letra = (char)(c - 3);  
            resultado += letra;
        }
        return resultado;
    }
    
    private void mostrarPista() {
        JOptionPane.showMessageDialog(null,
           "Pista: El mensaje usa un cifrado tipo César con desplazamiento de +3.");
    }
    
    private void actualizarTiempo() {
        lblTiempo.setText("Tiempo: " + tiempo);
    }

    private void crearTimer() {
        timer = new Timer(1000, e -> {
            if (tiempo > 0 && jugando) {
                tiempo--;
                actualizarTiempo();
            } else if (tiempo <= 0) {
                jugando = false;
                timer.stop();
                JOptionPane.showMessageDialog(null, "Se acabó el tiempo. Perdiste.");
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        txtCifrado = new javax.swing.JTextField();
        txtRespuesta = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        btnPista = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CryptoBreaker - Descifra el Mensaje");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 30, 242, 20);

        lblTiempo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTiempo.setForeground(new java.awt.Color(255, 255, 255));
        lblTiempo.setText("TIEMPO:");
        getContentPane().add(lblTiempo);
        lblTiempo.setBounds(370, 110, 90, 16);

        txtCifrado.setBackground(new java.awt.Color(51, 51, 51));
        txtCifrado.setForeground(new java.awt.Color(255, 255, 255));
        txtCifrado.setMinimumSize(new java.awt.Dimension(120, 25));
        txtCifrado.setPreferredSize(new java.awt.Dimension(120, 25));
        txtCifrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCifradoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCifrado);
        txtCifrado.setBounds(370, 180, 120, 25);

        txtRespuesta.setBackground(new java.awt.Color(51, 51, 51));
        txtRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        txtRespuesta.setPreferredSize(new java.awt.Dimension(120, 25));
        txtRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuestaActionPerformed(evt);
            }
        });
        getContentPane().add(txtRespuesta);
        txtRespuesta.setBounds(370, 250, 120, 25);

        btnIniciar.setBackground(new java.awt.Color(0, 0, 51));
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("INICIAR");
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar);
        btnIniciar.setBounds(90, 110, 100, 22);

        btnPista.setBackground(new java.awt.Color(0, 0, 51));
        btnPista.setForeground(new java.awt.Color(255, 255, 255));
        btnPista.setText("PISTA");
        btnPista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPistaMouseClicked(evt);
            }
        });
        btnPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPistaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPista);
        btnPista.setBounds(90, 250, 100, 22);

        btnVerificar.setBackground(new java.awt.Color(0, 0, 51));
        btnVerificar.setForeground(new java.awt.Color(255, 255, 255));
        btnVerificar.setText("VERIFICAR");
        btnVerificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerificarMouseClicked(evt);
            }
        });
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar);
        btnVerificar.setBounds(90, 180, 100, 22);

        BtnVolver.setBackground(new java.awt.Color(0, 0, 51));
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("VOLVER");
        BtnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnVolverMouseClicked(evt);
            }
        });
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver);
        BtnVolver.setBounds(90, 320, 100, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDO/Gemini_Generated_Image_5xh5pc5xh5pc5xh5.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtCifradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCifradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCifradoActionPerformed

    private void txtRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaActionPerformed

    private void btnPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPistaActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        // TODO add your handling code here:
        jugando = true;
        tiempo = 60;
        actualizarTiempo();
        txtCifrado.setText(new String(mensajeCifrado));
        txtRespuesta.setText("");
        timer.start();
        JOptionPane.showMessageDialog(null, "El juego ha comenzado. ¡Descifra el mensaje!");
    }//GEN-LAST:event_btnIniciarMouseClicked

    private void btnPistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPistaMouseClicked
        // TODO add your handling code here:
        mostrarPista();
    }//GEN-LAST:event_btnPistaMouseClicked

    private void btnVerificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerificarMouseClicked
        // TODO add your handling code here:
        if (!jugando) {
            JOptionPane.showMessageDialog(null, "Primero presiona INICIAR.");
            return;
        }
        String correcto = desencriptar(mensajeCifrado);
        String usuario = txtRespuesta.getText();

        if (usuario.equalsIgnoreCase(correcto)) {
            timer.stop();
            jugando = false;
            
            JOptionPane.showMessageDialog(null, "Correcto, has descifrado el mensaje.");
            PuntajesGlobales.modulo3 = tiempo;
        } else {
            JOptionPane.showMessageDialog(null, "Incorrecto, intenta de nuevo.");
        }
    }//GEN-LAST:event_btnVerificarMouseClicked

    private void BtnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolverMouseClicked
        // TODO add your handling code here:
        new Menu_principal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnVolverMouseClicked

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRYPTOBREAKER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRYPTOBREAKER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRYPTOBREAKER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRYPTOBREAKER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRYPTOBREAKER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPista;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JTextField txtCifrado;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
