/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab2_andres_gonzalez_david_buelvas_nombre3_apellido3_.nombre4_apellido4_.nombre5_apellido5;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class Menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        BtnVerPuntajes = new javax.swing.JButton();
        BtnAyuda = new javax.swing.JButton();
        btnModulo1 = new javax.swing.JButton();
        btnModulo2 = new javax.swing.JButton();
        btnModulo3 = new javax.swing.JButton();
        btnModulo4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("PhishHunter: Detecta el Engaño");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1250, 685));
        setResizable(false);
        setSize(new java.awt.Dimension(1250, 685));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CiberDefender Suite: Security Lab");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 40, 390, 47);

        btnSalir.setBackground(new java.awt.Color(0, 0, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(780, 620, 130, 22);

        BtnVerPuntajes.setBackground(new java.awt.Color(0, 0, 51));
        BtnVerPuntajes.setForeground(new java.awt.Color(255, 255, 255));
        BtnVerPuntajes.setText("VER PUNTAJES");
        BtnVerPuntajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnVerPuntajesMouseClicked(evt);
            }
        });
        getContentPane().add(BtnVerPuntajes);
        BtnVerPuntajes.setBounds(540, 620, 180, 22);

        BtnAyuda.setBackground(new java.awt.Color(0, 0, 51));
        BtnAyuda.setForeground(new java.awt.Color(255, 255, 255));
        BtnAyuda.setText("AYUDA");
        BtnAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAyudaMouseClicked(evt);
            }
        });
        getContentPane().add(BtnAyuda);
        BtnAyuda.setBounds(350, 620, 130, 22);

        btnModulo1.setBorderPainted(false);
        btnModulo1.setContentAreaFilled(false);
        btnModulo1.setFocusPainted(false);
        btnModulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModulo1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnModulo1);
        btnModulo1.setBounds(346, 102, 250, 240);

        btnModulo2.setBorderPainted(false);
        btnModulo2.setContentAreaFilled(false);
        btnModulo2.setFocusPainted(false);
        btnModulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModulo2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnModulo2);
        btnModulo2.setBounds(660, 100, 260, 240);

        btnModulo3.setBorderPainted(false);
        btnModulo3.setContentAreaFilled(false);
        btnModulo3.setFocusPainted(false);
        btnModulo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModulo3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnModulo3);
        btnModulo3.setBounds(345, 372, 250, 230);

        btnModulo4.setBorderPainted(false);
        btnModulo4.setContentAreaFilled(false);
        btnModulo4.setFocusPainted(false);
        btnModulo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModulo4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnModulo4);
        btnModulo4.setBounds(660, 370, 260, 230);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FirewallMatrix: La Muralla Digital");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(970, 210, 230, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CryptoBreaker - Descifra el Mensaje");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 480, 250, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SecureLog Analyzer - Detección Forense");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(950, 480, 270, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PhishHunter: Detecta el Engaño");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 210, 210, 20);

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDO/Gemini_Generated_Image_j616zuj616zuj616.png"))); // NOI18N
        getContentPane().add(FONDO);
        FONDO.setBounds(0, 0, 1248, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModulo1ActionPerformed
        // TODO add your handling code here:
        new PANTALLA1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModulo1ActionPerformed

    private void btnModulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModulo2ActionPerformed
        // TODO add your handling code here:
        new PANTALLA2().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModulo2ActionPerformed

    private void btnModulo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModulo3ActionPerformed
        // TODO add your handling code here:
        new CRYPTOBREAKER().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModulo3ActionPerformed

    private void btnModulo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModulo4ActionPerformed
        // TODO add your handling code here:
        new SECURELOG().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModulo4ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Saliendo del sistema...");
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void BtnVerPuntajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVerPuntajesMouseClicked
        // TODO add your handling code here:
        new VerPuntaje().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnVerPuntajesMouseClicked

    private void BtnAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAyudaMouseClicked
        // TODO add your handling code here:
        new AYUDA().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnAyudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAyuda;
    private javax.swing.JButton BtnVerPuntajes;
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton btnModulo1;
    private javax.swing.JButton btnModulo2;
    private javax.swing.JButton btnModulo3;
    private javax.swing.JButton btnModulo4;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    private static class FIREWALLMATRIX {

        public FIREWALLMATRIX() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
