/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab2_andres_gonzalez_david_buelvas_nombre3_apellido3_.nombre4_apellido4_.nombre5_apellido5;

import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class PANTALLA2 extends javax.swing.JFrame {

    /**
     * Creates new form PANTALLA2
     */
    public PANTALLA2() {
        initComponents();
        jTable1.setEnabled(false);
        setLocationRelativeTo(null);
        setResizable(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = jTable1.getSelectedRow();
                int columna = jTable1.getSelectedColumn();

                if (fila != -1 && columna != -1) {
                    verificarBloqueo(fila, columna, jTable1);
                }
            }
        });
    }

    int[][] matrizPuertos = new int[5][5];
    int aciertos = 0;
    int errores = 0;
    int totalComprometidos = 0;

    private void generarAtaqueAleatorio() {
        totalComprometidos = 0;

        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {

                // 30% de probabilidad de que el puerto esté comprometido
                int valor = (Math.random() < 0.30) ? 1 : 0;

                matrizPuertos[i][j] = valor;

                if (valor == 1) {
                    totalComprometidos++;
                }
            }
        }

        actualizarTabla();
    }

    private void verificarBloqueo(int fila, int columna, javax.swing.JTable tabla) {
        if (matrizPuertos[fila][columna] == 1) {
            aciertos++;

            // Cambiar color o icono (animación simple)
            jTable1.setValueAt("O", fila, columna);

        } else {
            errores++;

            // Animación negativa
            jTable1.setValueAt("❌", fila, columna);
        }
        lblAciertos.setText("ACIERTOS: " + aciertos);
        lblErrores.setText("ERRORES: " + errores);
        verificarResultado();
        ocultarValoresTabla();
    }

    private void actualizarTabla() {
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                jTable1.setValueAt(matrizPuertos[i][j], i, j);
            }
        }
    }

    private void verificarResultado() {
        if (aciertos + errores == totalComprometidos) {

            double porcentaje = (aciertos * 100.0) / totalComprometidos;

            if (porcentaje >= 80) {
                JOptionPane.showMessageDialog(this, "✅ Red protegida con éxito");
            } else {
                JOptionPane.showMessageDialog(this, "❌ La red fue vulnerada");
            }
            PuntajesGlobales.modulo2 = aciertos;
        }
    }

    private void jTablePuertosMouseClicked(java.awt.event.MouseEvent evt) {
        int fila = jTable1.getSelectedRow();
        int columna = jTable1.getSelectedColumn();

        verificarBloqueo(fila, columna, jTable1);
    }

    private void ocultarValoresTabla() {
        jTable1.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {

            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus,
                    int row, int column) {

                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // Si es 0 o 1: ocultarlo
                if ("0".equals(value.toString()) || "1".equals(value.toString())) {
                    setText("");
                } // Si es icono o texto, mostrarlo normal
                else {
                    setText(value.toString());
                }

                setHorizontalAlignment(CENTER);
                return this;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnInicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblAciertos = new javax.swing.JLabel();
        lblErrores = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 230, 164, 90);

        BtnInicio.setBackground(new java.awt.Color(0, 0, 51));
        BtnInicio.setForeground(new java.awt.Color(255, 255, 255));
        BtnInicio.setText("INICIAR");
        BtnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnInicioMouseClicked(evt);
            }
        });
        getContentPane().add(BtnInicio);
        BtnInicio.setBounds(50, 110, 100, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FirewallMatrix: La Muralla Digital");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 40, 230, 20);

        lblAciertos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAciertos.setForeground(new java.awt.Color(255, 255, 255));
        lblAciertos.setText("ACIERTOS: ");
        getContentPane().add(lblAciertos);
        lblAciertos.setBounds(50, 170, 100, 16);

        lblErrores.setBackground(new java.awt.Color(0, 0, 51));
        lblErrores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrores.setForeground(new java.awt.Color(255, 255, 255));
        lblErrores.setText("ERRORES: ");
        getContentPane().add(lblErrores);
        lblErrores.setBounds(450, 170, 100, 16);

        BtnSalir.setBackground(new java.awt.Color(0, 0, 51));
        BtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir.setText("VOLVER");
        BtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalirMouseClicked(evt);
            }
        });
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir);
        BtnSalir.setBounds(450, 110, 100, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDO/Gemini_Generated_Image_5xh5pc5xh5pc5xh5.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnInicioMouseClicked
        // TODO add your handling code here:
        aciertos = 0;
        errores = 0;
        generarAtaqueAleatorio();
        ocultarValoresTabla();
        actualizarTabla();
        jTable1.setEnabled(true);
    }//GEN-LAST:event_BtnInicioMouseClicked

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalirMouseClicked
        // TODO add your handling code here:
        new Menu_principal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PANTALLA2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PANTALLA2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PANTALLA2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PANTALLA2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PANTALLA2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInicio;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAciertos;
    private javax.swing.JLabel lblErrores;
    // End of variables declaration//GEN-END:variables
}
