/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab2_andres_gonzalez_david_buelvas_nombre3_apellido3_.nombre4_apellido4_.nombre5_apellido5;

import java.io.FileWriter;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class PANTALLA1 extends javax.swing.JFrame {

    int tiempo = 60, vidas = 3, puntaje = 0;
    boolean play = false;
    private final String[] eventos = {"Ataque de phishing", "Malware detectado", "Acceso no autorizado", "Trafico legitimo", "Acceso autorizado", "Spyware", "Ransomware", "Autenticacion de dos factores", "Firewall", "Cifrado de datos"};
    private String[] v = new String[10];
    int fila = 0;
    DefaultListModel<String> modeloEventos;
    DefaultListModel<String> modeloAmenazas;

    public PANTALLA1() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        for (int i = 0; i < v.length; i++) {
            v[i] = "";
        }
        modeloEventos = new DefaultListModel<>();
        modeloAmenazas = new DefaultListModel<>();

// Llenar lista de eventos
        for (String evento : eventos) {
            modeloEventos.addElement(evento);
        }

        listaEventosDeSeguridad.setModel(modeloEventos);
        listaAmenaza.setModel(modeloAmenazas);
    }

    private boolean esPhishing(String texto) {
        if (texto == null || texto.isEmpty()) {
            return false;
        }

        texto = texto.toLowerCase();

        String[] sospechosas = {
            "contraseña", "password", "urgente", "clic",
            "aquí", "link", "verificar", "premio", "ganaste", "actualizar"
        };

        for (String palabra : sospechosas) {
            if (texto.contains(palabra)) {
                return true;
            }
        }
        return false;
    }

    private void actualizarPuntaje(boolean acierto) {
        if (acierto) {
            puntaje++;
        } else {
            puntaje--;
            if (puntaje < 0) {
                puntaje = 0;
            }
        }
        lblpuntaje.setText("PUNTAJE: " + puntaje);
    }

    private void guardarResultado(String evento, String tipo) {
        try {
            FileWriter fw = new FileWriter("resultados_modulo1.txt", true);
            fw.write("Evento: " + evento + " | Clasificación: " + tipo + " | Puntaje: " + puntaje + "\n");
            fw.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar el resultado.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblpuntaje = new javax.swing.JLabel();
        lblvidas = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEventosDeSeguridad = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAmenaza = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PhishHunter: Detecta el Engaño");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 20, 210, 20);

        lblpuntaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblpuntaje.setForeground(new java.awt.Color(255, 255, 255));
        lblpuntaje.setText("PUNTAJE: ");
        getContentPane().add(lblpuntaje);
        lblpuntaje.setBounds(20, 130, 110, 16);

        lblvidas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblvidas.setForeground(new java.awt.Color(255, 255, 255));
        lblvidas.setText("VIDAS: ");
        getContentPane().add(lblvidas);
        lblvidas.setBounds(250, 130, 90, 16);

        btnInicio.setBackground(new java.awt.Color(0, 0, 51));
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("INICIAR");
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio);
        btnInicio.setBounds(20, 70, 110, 22);

        btnReiniciar.setBackground(new java.awt.Color(0, 0, 51));
        btnReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnReiniciar.setText("REINICIAR");
        btnReiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReiniciarMouseClicked(evt);
            }
        });
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciar);
        btnReiniciar.setBounds(250, 70, 110, 22);

        btnSalir.setBackground(new java.awt.Color(0, 0, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("VOLVER");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(470, 70, 110, 22);

        listaEventosDeSeguridad.setBackground(new java.awt.Color(51, 51, 51));
        listaEventosDeSeguridad.setForeground(new java.awt.Color(255, 255, 255));
        listaEventosDeSeguridad.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ataque de phishing", "Malware detectado", "Acceso no autorizado", "Trafico legitimo", "Acceso autorizado", "Spyware", "Ransomware", "Autenticacion de dos factores", "Firewall", "Cifrado de datos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaEventosDeSeguridad);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 170, 203, 187);

        listaAmenaza.setBackground(new java.awt.Color(51, 51, 51));
        listaAmenaza.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(listaAmenaza);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(250, 170, 330, 187);

        btnAgregar.setBackground(new java.awt.Color(0, 0, 51));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(470, 130, 110, 22);

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDO/Gemini_Generated_Image_5xh5pc5xh5pc5xh5.png"))); // NOI18N
        getContentPane().add(FONDO);
        FONDO.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        // TODO add your handling code here:
        if (play == false) {
            play = true;
            vidas = 3;
            puntaje = 0;
            tiempo = 60;
            lblpuntaje.setText("PUNTAJE: " + puntaje);
            lblvidas.setText("VIDAS: " + vidas);
            fila = 0;
            for (int i = 0; i < v.length; i++) {
                v[i] = "";
            }
            listaAmenaza.setModel(modeloAmenazas);
        }
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnReiniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReiniciarMouseClicked
        // TODO add your handling code here:
        if (play == false) {
            JOptionPane.showMessageDialog(null, "Presiona INICIO para comenzar.");
            return;
        }
        vidas = 3;
        puntaje = 0;
        lblpuntaje.setText("PUNTAJE: 0");
        lblvidas.setText("VIDAS: 3");
        play = false;
        JOptionPane.showMessageDialog(null, "Juego reiniciado.");
        modeloEventos.clear();
        modeloAmenazas.clear();

        // Volver a cargar los eventos originales
        for (String evento : eventos) {
            modeloEventos.addElement(evento);
        }

        JOptionPane.showMessageDialog(null, "Juego reiniciado correctamente.");
    }//GEN-LAST:event_btnReiniciarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        new Menu_principal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        if (play == false) {
            JOptionPane.showMessageDialog(null, "Presiona INICIO para comenzar.");
            return;
        }
        String seleccionado = listaEventosDeSeguridad.getSelectedValue();

        if (seleccionado == null) {
            JOptionPane.showMessageDialog(null, "Selecciona un evento primero.");
            return;
        }

        boolean esAmenaza = seleccionado.equals("Ataque de phishing")
                || seleccionado.equals("Malware detectado")
                || seleccionado.equals("Acceso no autorizado")
                || seleccionado.equals("Spyware")
                || seleccionado.equals("Ransomware");

        if (esAmenaza) {
            modeloAmenazas.addElement(seleccionado);
            modeloEventos.removeElement(seleccionado);
            puntaje++;
            lblpuntaje.setText("PUNTAJE: " + puntaje);
            JOptionPane.showMessageDialog(null, "✅ Amenaza detectada correctamente");
        } else {
            modeloEventos.removeElement(seleccionado);
            vidas--;
            lblvidas.setText("VIDAS: " + vidas);
            JOptionPane.showMessageDialog(null, "❌ Esto no es una amenaza");
        }

        // Condición de derrota
        if (vidas <= 0) {
            JOptionPane.showMessageDialog(null, "La red fue comprometida.");
            play = false;
        }

        // Condición de victoria
        if (modeloAmenazas.size() >= 5) {
            JOptionPane.showMessageDialog(null, "Felicidades, has asegurado la red");
            PuntajesGlobales.modulo1 = puntaje;
            play = false;
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PANTALLA1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PANTALLA1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PANTALLA1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PANTALLA1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PANTALLA1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblpuntaje;
    private javax.swing.JLabel lblvidas;
    private javax.swing.JList<String> listaAmenaza;
    private javax.swing.JList<String> listaEventosDeSeguridad;
    // End of variables declaration//GEN-END:variables
}
