/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab2_andres_gonzalez_david_buelvas_nombre3_apellido3_.nombre4_apellido4_.nombre5_apellido5;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;

/**
 *
 * @author HP
 */
public class SECURELOG extends javax.swing.JFrame {
    private ArrayList<String> eventosList = new ArrayList<>();
    private ArrayList<String> categoriasList = new ArrayList<>();
    private DefaultTableModel modelo;
    /**
     * Creates new form SECURELOG
     */
    public SECURELOG() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Módulo 4 - SecureLog Analyzer");
        modelo = new DefaultTableModel();
        modelo.addColumn("Evento");
        modelo.addColumn("Clasificación");
        tablaLogs.setModel(modelo);
        tablaLogs.setRowHeight(28);
        tablaLogs.getColumnModel().getColumn(0).setPreferredWidth(300);
        tablaLogs.getColumnModel().getColumn(1).setPreferredWidth(120);
        String[] opciones = {"Normal", "Sospechoso", "Crítico"};
        JComboBox<String> combo = new JComboBox<>(opciones);
        tablaLogs.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(combo));
    }
   private String clasificarEvento(String evento) {
        if (evento == null) return "Normal";
        String e = evento.toLowerCase();
        String[] criticas = {"ataque", "malware", "fuerza bruta", "infectado", "ransomware", "exploit", "comprometido"};
        for (String k : criticas) if (e.contains(k)) return "Crítico";
        String[] sospecha = {"sospech", "fallido", "intent", "alert", "anómalo", "anormal", "peligroso", "usuario ingresó", "contraseña incorrecta"};
        for (String k : sospecha) if (e.contains(k)) return "Sospechoso";
        return "Normal";
    }
   
   private void mostrarResumen() {
        int normales = 0, sospechosos = 0, criticos = 0;
        for (String cat : categoriasList) {
            if (cat == null) continue;
            switch (cat) {
                case "Normal": normales++; break;
                case "Sospechoso": sospechosos++; break;
                case "Crítico": criticos++; break;
                default: break;
            }
        }
        String mensaje = "Resumen del análisis:\n" + "Normales: " + normales + "\n" + "Sospechosos: " + sospechosos + "\n" + "Críticos: " + criticos;
        JOptionPane.showMessageDialog(this, mensaje);
    }

   private void cargarLogsDesdeArchivo() {
        eventosList.clear();
        categoriasList.clear();
        modelo.setRowCount(0); 

        try (BufferedReader br = new BufferedReader(new FileReader("logs.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                if (linea.trim().isEmpty()) continue;
                eventosList.add(linea.trim());
                categoriasList.add(""); 
                modelo.addRow(new Object[]{linea.trim(), ""});
            }
            if (eventosList.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El archivo logs.txt está vacío o no contiene eventos.");
            } else {
                JOptionPane.showMessageDialog(this, "Logs cargados: " + eventosList.size());
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error leyendo logs.txt: " + ex.getMessage());
        }
    }

   private void clasificarTodos() {
        PuntajesGlobales.modulo4 = eventosList.size();
        if (eventosList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay eventos cargados. Usa 'Cargar Logs' primero.");
            return;
        }
        for (int i = 0; i < eventosList.size(); i++) {
            String evento = eventosList.get(i);
            String categoria = clasificarEvento(evento);
            categoriasList.set(i, categoria);
            modelo.setValueAt(categoria, i, 1); 
        }
        JOptionPane.showMessageDialog(this, "Clasificación finalizada.");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLogs = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        btnClasificar = new javax.swing.JButton();
        btnResumen = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        tablaLogs.setBackground(new java.awt.Color(51, 51, 51));
        tablaLogs.setForeground(new java.awt.Color(255, 255, 255));
        tablaLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaLogs);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 90, 500, 210);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SecureLog Analyzer - Detección Forense");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 40, 280, 20);

        btnCargar.setBackground(new java.awt.Color(0, 0, 51));
        btnCargar.setForeground(new java.awt.Color(255, 255, 255));
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar);
        btnCargar.setBounds(20, 330, 110, 22);

        btnClasificar.setBackground(new java.awt.Color(0, 0, 51));
        btnClasificar.setForeground(new java.awt.Color(255, 255, 255));
        btnClasificar.setText("Clasificar");
        btnClasificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClasificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnClasificar);
        btnClasificar.setBounds(170, 330, 110, 22);

        btnResumen.setBackground(new java.awt.Color(0, 0, 51));
        btnResumen.setForeground(new java.awt.Color(255, 255, 255));
        btnResumen.setText("Resumen");
        btnResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumenActionPerformed(evt);
            }
        });
        getContentPane().add(btnResumen);
        btnResumen.setBounds(320, 330, 110, 22);

        BtnVolver.setBackground(new java.awt.Color(0, 0, 51));
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("Volver");
        BtnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnVolverMouseClicked(evt);
            }
        });
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver);
        BtnVolver.setBounds(470, 330, 110, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDO/Gemini_Generated_Image_5xh5pc5xh5pc5xh5.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        cargarLogsDesdeArchivo();
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnClasificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClasificarActionPerformed
        // TODO add your handling code here:
        if (eventosList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Primero carga los logs.");
        return;
    }
        int aciertos = 0;
        int errores = 0;
          for (int i = 0; i < modelo.getRowCount(); i++) {
           String evento = (String) modelo.getValueAt(i, 0);
           String respuestaUsuario = (String) modelo.getValueAt(i, 1);
        if (respuestaUsuario == null || respuestaUsuario.trim().isEmpty()) {
            errores++;
            continue;
        }
        String clasificacionReal = clasificarEvento(evento);
        if (respuestaUsuario.equalsIgnoreCase(clasificacionReal)) {
            aciertos++;
        } else {
            errores++;
        }
    }
        int total = aciertos + errores;
        int porcentaje = (aciertos * 100) / total;
    JOptionPane.showMessageDialog(this,
            "Resultados del jugador:\n\n" +
            "Aciertos: " + aciertos + "\n" +
            "Errores: " + errores + "\n" +
            "Precisión: " + porcentaje + "%");
    PuntajesGlobales.modulo4 = aciertos;
    }//GEN-LAST:event_btnClasificarActionPerformed

    private void btnResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumenActionPerformed
        // TODO add your handling code here:
        int normales = 0, sospechosos = 0, criticos = 0, vacios = 0;
          for (int i = 0; i < modelo.getRowCount(); i++) {
          String c = (String) modelo.getValueAt(i, 1);
          if (c == null || c.trim().isEmpty()) {
            vacios++;
        } else if (c.equals("Normal")) {
            normales++;
        } else if (c.equals("Sospechoso")) {
            sospechosos++;
        } else if (c.equals("Crítico")) {
            criticos++;
        }
    }
          JOptionPane.showMessageDialog(this,
          "Resumen de clasificaciones del usuario:\n\n" +
          "Normal: " + normales + "\n" +
          "Sospechoso: " + sospechosos + "\n" +
          "Crítico: " + criticos + "\n" +
          "Sin clasificar: " + vacios);
    }//GEN-LAST:event_btnResumenActionPerformed

    private void BtnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolverMouseClicked
        // TODO add your handling code here:
        new Menu_principal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnVolverMouseClicked

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SECURELOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SECURELOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SECURELOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SECURELOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SECURELOG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnClasificar;
    private javax.swing.JButton btnResumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaLogs;
    // End of variables declaration//GEN-END:variables
}
