/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab2_andres_gonzalez_david_buelvas_nombre3_apellido3_.nombre4_apellido4_.nombre5_apellido5;

/**
 *
 * @author andre
 */
public class VerPuntaje extends javax.swing.JFrame {

    /**
     * Creates new form VerPuntaje
     */
    public VerPuntaje() {
        initComponents();
        actualizarPuntajes();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    private void actualizarPuntajes() {
        lblM1.setText("PhishHunter: Detecta el Engaño: " + PuntajesGlobales.modulo1);
        lblM2.setText("FirewallMatrix: La Muralla Digital: " + PuntajesGlobales.modulo2);
        lblM3.setText("CryptoBreaker: Desencripta el Código: " + PuntajesGlobales.modulo3);
        lblM4.setText("SecureLog Analyzer: Detección Forense: " + PuntajesGlobales.modulo4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblM1 = new javax.swing.JLabel();
        lblM2 = new javax.swing.JLabel();
        lblM3 = new javax.swing.JLabel();
        lblM4 = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PUNTAJES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 30, 80, 20);

        lblM1.setForeground(new java.awt.Color(255, 255, 255));
        lblM1.setText("PhishHunter: Detecta el Engaño: ");
        getContentPane().add(lblM1);
        lblM1.setBounds(20, 90, 310, 16);

        lblM2.setForeground(new java.awt.Color(255, 255, 255));
        lblM2.setText("FirewallMatrix: La Muralla Digital: ");
        getContentPane().add(lblM2);
        lblM2.setBounds(20, 150, 310, 16);

        lblM3.setForeground(new java.awt.Color(255, 255, 255));
        lblM3.setText("CryptoBreaker - Descifra el Mensaje: ");
        getContentPane().add(lblM3);
        lblM3.setBounds(20, 210, 310, 16);

        lblM4.setForeground(new java.awt.Color(255, 255, 255));
        lblM4.setText("SecureLog Analyzer - Detección Forense: ");
        getContentPane().add(lblM4);
        lblM4.setBounds(20, 270, 310, 16);

        BtnSalir.setBackground(new java.awt.Color(0, 0, 51));
        BtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir.setText("VOLVER");
        BtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalirMouseClicked(evt);
            }
        });
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir);
        BtnSalir.setBounds(240, 320, 110, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDO/Gemini_Generated_Image_5xh5pc5xh5pc5xh5.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalirMouseClicked
        // TODO add your handling code here:
        new Menu_principal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnSalirMouseClicked

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerPuntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerPuntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerPuntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerPuntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerPuntaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblM1;
    private javax.swing.JLabel lblM2;
    private javax.swing.JLabel lblM3;
    private javax.swing.JLabel lblM4;
    // End of variables declaration//GEN-END:variables
}
